name: Daily Weather Agent Run

on:
  schedule:
    - cron: '10 3 * * *'  # Runs every day at 8:30 AM IST (3:00 AM UTC)
  workflow_dispatch:  # Optional: lets you run manually

jobs:
  run-weather-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main_agent.py
        run: |
          python main_agent.py
