name: Daily Weather Agent Run

on:
  schedule:
    - cron: '00 3 * * *'  # 8:30 AM IST = 3:00 AM UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-weather-agent:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main_agent.py
        run: |
          python main_agent.py
